remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
logo: https://lavanyamenon15.github.io/ProfilePic.png
title: Lavanya Menon
description: |
  <br> <b>Education:</b> 4th Year Honours Computer Science Major at the University of British Columbia <br> <br>
  <b>Email:</b> lavanyamenon1215@gmail.com <br> <br>
  <b>LinkedIn:</b> <a href="https://www.linkedin.com/in/lavanya-menon-6973a01b2/"> https://www.linkedin.com/in/lavanya-menon-6973a01b2/ </a> <br> <br>
