remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
logo: https://lavanyamenon15.github.io/ProfilePic.jpg
title: Lavanya Menon
description: |
  **Education:** 4th Year Honours Computer Science Major at the University of British Columbia  
  **Email:** lavanyamenon1215@gmail.com
  **LinkedIn:* https://www.linkedin.com/in/lavanya-menon-6973a01b2/
