remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
logo: https://lavanyamenon15.github.io/ProfilePic.jpg
title: Lavanya Menon
description: |
  <b>Education:</b> 4th Year Honours Computer Science Major at the University of British Columbia
  
  <b>Email:</b> lavanyamenon1215@gmail.com
  
  <b>LinkedIn:</b> https://www.linkedin.com/in/lavanya-menon-6973a01b2/
