remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

logo: https://lavanyamenon15.github.io/ProfilePic.jpg
title: Lavanya Menon
description: | 
Hello! I'm Lavanya, a fourth year student at The University of British Columbia pursuing an Honours Bachelor of Science (BSc) majoring in Computer Science. I am a passionate and driven person who consistently strives to learn more about various facets of computer science as well as their applications. In the past, I have done back-end database development, full-stack bug resolution, algorithmic problem solving, front-end UI building, database development, and project management.
